version: "3.6"

x-service:
    &default-service
    tty: true
    stdin_open: true
    volumes:
        - type: bind
          source: ./scripts
          target: ${SCRIPT_ROOT}
          read_only: true
    env_file: .env

services:
    # the primary cluster (but might switch)
    node1:
        image: "pg"
        ports:
            - "5432"
            - "22"
        <<: *default-service
        hostname: node1
        networks:
            internal_net:
            external_net:
                ipv4_address: "${VIP}"

    # the secondary cluster (but might switch)
    node2:
        image: "pg"
        ports:
            - "5432"
            - "22"
        <<: *default-service
        hostname: node2
        networks:
            internal_net:


    backup:
        image: "barman"
        ports:
            - "22"
        <<: *default-service
        hostname: backup
        networks:
            internal_net:

networks:
    # internal network for primary-standby replication
    internal_net:
        internal: true
    # external interface, there is always only one ip (VIP) is set for 
    # the backend, and is bound to the primary db.
    external_net:
        driver: bridge
        ipam:
            config:
                - subnet: "${SUBNET}"
