version: "3.6"

x-service:
    &default-service
    tty: true
    stdin_open: true
    volumes:
        - type: bind
          source: ./scripts
          target: ${SCRIPT_ROOT}
          read_only: true
        - type: volume
          source: backup
          target: ${BACKUP_ROOT}
    env_file: .env

services:
    # just for manipulating the volume
    p0:
        <<: *default-service
        image: "pg-base"

    # the primary cluster (but might switch)
    p1:
        <<: *default-service
        image: "pg"
        hostname: p1
        ports:
            - "5432"
        networks:
            internal_net:
            external_net:
                ipv4_address: "${VIP}"

    # the secondary cluster (but might switch)
    p2:
        <<: *default-service
        image: "pg"
        ports:
            - "5432"
        hostname: p2
        networks:
            internal_net:

networks:
    # internal network for primary-standby replication
    internal_net:
        internal: true
    # external interface, there is always only one ip (VIP) is set for 
    # the backend, and is bound to the primary db.
    external_net:
        driver: bridge
        ipam:
            config:
                - subnet: "${SUBNET}"

volumes:
  backup:
